check50:
  files: &check50_files
    - !exclude "*"
    - !require ReadAFile.java
    - !require WriteAFile.java
    - !require CountAndPrint.java
    - !include LoopCount.java

submit50:
  files: *check50_files
