check50: 
  files: &check50_files
    - !exclude "*"
    - !require Shape.java
    - !require Rectangle.java
    - !require ShapeClient.java
    - !require README.md
    - !require Circle.java
    - !include "*.png"
    - !include "*.jpg"
    - !include "*.jpeg"

submit50:
  files: *check50_files
