check50: 
  files: &check50_files
    - !exclude "*"
    - !include *.java
    - !require RoundBalloon.java
    - !require OvalBalloon.java
    - !require SquareBalloon.java
    - !require FancyBalloon.java

submit50:
  files: *check50_files
